server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/billing_software
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
server.servlet.context-path=/api/v1.0

aws.access.key=efw56413e5g4f4ef3sef65es9gf84es6g8s
aws.secret.key=3445345554345263415132151df5g1dsg56sfg
aws.region=ap-south-1
aws.bucket.name=Lunariaaaa

jwt.secret.key=lunaria_secret_key

razorpay.key.id=51d5641d654sg4sg5sg1ges
razorpay.key.secret=42g5s4g1s5f035esgf1es5f1sef

