# Configuración para desarrollo
spring.datasource.url=jdbc:mysql://localhost:3306/Innovation_Fusion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SENA

# Logging para desarrollo
logging.level.com.backend.proyect=DEBUG
logging.level.org.springframework.security=DEBUG