# Configuración para producción
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Logging para producción
logging.level.com.backend.proyect=INFO
logging.level.org.springframework.security=WARN